In [5]:
import numpy as np


create a vocabulary

In [6]:
vocab = {
    "I" : 0,
    "love" : 1,
    "AI" : 2
}

Create an embedding matrix

In [11]:
embedding_matrix = np.array([
    [0.2, 0.1, 0.4], # I
    [0.7, 0.3, 0.8], # love
    [0.9, 0.6, 0.2] # AI
])

Now our text

In [8]:
text = "I love AI"

tokenize

In [9]:
tokens = text.split()

print(tokens)

['I', 'love', 'AI']


Tokens -> Token Id

In [10]:
token_ids = [vocab[token] for token in tokens]

print(token_ids)

[0, 1, 2]


Token Ids -> Embeddings

In [13]:
embeddings = embedding_matrix[token_ids]

print(embeddings)

[[0.2 0.1 0.4]
 [0.7 0.3 0.8]
 [0.9 0.6 0.2]]


Cell 7 — Dot product of embeddings

In [14]:
I = embeddings[0]
love = embeddings[1]

dot_product = np.dot(I, love)

print("I embedding", I)
print("love embedding", I)
print("dot product", dot_product)

I embedding [0.2 0.1 0.4]
love embedding [0.2 0.1 0.4]
dot product 0.49000000000000005


Cell 8 — Complete pipeline

In [15]:
print("Text:", text)
print("Tokens:", tokens)
print("Token IDs:", token_ids)
print("Embeddings:")
print(embeddings)

Text: I love AI
Tokens: ['I', 'love', 'AI']
Token IDs: [0, 1, 2]
Embeddings:
[[0.2 0.1 0.4]
 [0.7 0.3 0.8]
 [0.9 0.6 0.2]]


Cell 9 — Concept summary

# Day 5 Summary

Text
↓
Tokens
↓
Token IDs
↓
Embeddings
↓
Vectors
↓
Vector Mathematics

Key concepts:

- A token is a piece of text.
- A token ID is a numerical identifier for a token.
- An embedding is a vector representing a token.
- A vector is a mathematical object containing numbers.
- Multiple token embeddings form a matrix.
- Dot product takes two same-dimensional vectors and produces a single number.
- Vector mathematics allows a neural network to work with language numerically.

Important distinction:

Embedding = a vector used as a representation.

Example:

cat → [0.2, 0.7, 0.4]

[0.2, 0.7, 0.4] is both:
- a vector mathematically
- an embedding because it represents "cat"