# Day 6 — Matrices

A matrix is a rectangular arrangement of numbers.

Example:

[
    [0.2, 0.4, 0.6],
    [0.1, 0.3, 0.5],
    [0.7, 0.8, 0.9]
]

This matrix has:
- 3 rows
- 3 columns

Therefore its shape is 3 × 3.

A vector is a single list of numbers.
A matrix can contain multiple vectors arranged as rows or columns.

In [16]:
import numpy as np

matrix = np.array([
     [0.2, 0.4, 0.6],
    [0.1, 0.3, 0.5],
    [0.7, 0.8, 0.9]

])

print(matrix)

[[0.2 0.4 0.6]
 [0.1 0.3 0.5]
 [0.7 0.8 0.9]]


## Rows and Columns

For the matrix:

[
    [0.2, 0.4, 0.6],
    [0.1, 0.3, 0.5],
    [0.7, 0.8, 0.9]
]

Rows:
- Row 1 = [0.2, 0.4, 0.6]
- Row 2 = [0.1, 0.3, 0.5]
- Row 3 = [0.7, 0.8, 0.9]

Columns:
- Column 1 = [0.2, 0.1, 0.7]
- Column 2 = [0.4, 0.3, 0.8]
- Column 3 = [0.6, 0.5, 0.9]

In [17]:
print("Matrix shape", matrix.shape)

Matrix shape (3, 3)


## Embeddings and Matrices

Each token can have an embedding vector.

Example:

cat → [0.2, 0.4, 0.6]
dog → [0.1, 0.3, 0.5]
car → [0.7, 0.8, 0.9]

When multiple embedding vectors are arranged together,
they form a matrix.

Therefore:

Multiple vectors → Matrix

## Sentence as a Matrix

Suppose a sentence has 3 tokens and each token
has a 4-dimensional embedding.

Then the embedding matrix has shape:

3 × 4

because:

3 = number of tokens
4 = embedding dimensions

So:

Number of tokens × Embedding dimension
= Embedding matrix shape

In [18]:
print("First row: ", matrix[0])
print("Second row: ", matrix[1])
print("Third row: ", matrix[2])

First row:  [0.2 0.4 0.6]
Second row:  [0.1 0.3 0.5]
Third row:  [0.7 0.8 0.9]


## Accessing Matrix Rows and Columns

NumPy uses:

matrix[rows, columns]

The `:` means "all".

Therefore:

matrix[:, 0]

means:

- all rows
- column 0

Example:

[
 [0.2, 0.4, 0.6],
 [0.1, 0.3, 0.5],
 [0.7, 0.8, 0.9]
]

matrix[:, 0]

returns:

[0.2, 0.1, 0.7]

In [19]:
print("First columns", matrix[:, 0])
print("Second columns", matrix[:, 1])

First columns [0.2 0.1 0.7]
Second columns [0.4 0.3 0.8]


## Matrix Addition

Matrix addition works by adding corresponding elements.

Example:

A =
[
 [1, 2],
 [3, 4]
]

B =
[
 [5, 6],
 [7, 8]
]

A + B =

[
 [1+5, 2+6],
 [3+7, 4+8]
]

=
[
 [6, 8],
 [10, 12]
]

For basic matrix addition, both matrices must have the same shape.

In [20]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = A + B

print("A: ")
print(A)

print("\nB: ")
print(B)

print("\nC: ")
print(C)



A: 
[[1 2]
 [3 4]]

B: 
[[5 6]
 [7 8]]

C: 
[[ 6  8]
 [10 12]]


## Scalar Multiplication

A scalar is a single number.

Scalar multiplication means multiplying every element
of a matrix by the scalar.

Example:

A =
[
 [1, 2],
 [3, 4]
]

3 × A =

[
 [3, 6],
 [9, 12]
]

The shape does not change.

A is 2 × 2.
3 × A is also 2 × 2.

In [21]:
A = np.array([
    [1, 2],
    [3, 4]
])

result = 3 * A

print("A: ")
print(A)

print("\nresult: ")
print(result)

print("\nshape: ", result.shape)

A: 
[[1 2]
 [3 4]]

result: 
[[ 3  6]
 [ 9 12]]

shape:  (2, 2)


# Matrix Multiplication

For matrix multiplication:

A = m × n
B = n × p

The inside dimensions must match:

(m × n) × (n × p)

The resulting matrix has the outside dimensions:

m × p

Example:

A = 2 × 2
B = 2 × 2

Therefore:

A × B = 2 × 2

## How Matrix Multiplication Works

Matrix multiplication uses dot products.

For:

A =
[
 [1, 2],
 [3, 4]
]

B =
[
 [5, 6],
 [7, 8]
]

The top-left result:

[1, 2] · [5, 7]
= (1×5) + (2×7)
= 19

The top-right result:

[1, 2] · [6, 8]
= (1×6) + (2×8)
= 22

The bottom-left result:

[3, 4] · [5, 7]
= 43

The bottom-right result:

[3, 4] · [6, 8]
= 50

Therefore:

A × B =
[
 [19, 22],
 [43, 50]
]

Matrix multiplication can be understood as multiple
dot products between rows of the first matrix and
columns of the second matrix.

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = A @ B

print("A: ")
print(A)

print("\nB: ")
print(B)

print("\nA x B: ")
print(result)



## Matrix Multiplication vs Element-wise Multiplication

These are different operations.

Element-wise multiplication:

A * B

multiplies corresponding elements.

Matrix multiplication:

A @ B

uses rows of A and columns of B and calculates
dot products.

Example:

A @ B

means matrix multiplication.

A * B

means element-wise multiplication in NumPy.

In [22]:
A = np.array([
    [2, 3],
    [4, 5]
])

B = np.array([
    [6, 7],
    [8, 9]
])

print("Element wise multiplication: ")
print(A * B)

print("\nmatrix multiplication: ")
print(A @ B)


Element wise multiplication: 
[[12 21]
 [32 45]]

matrix multiplication: 
[[36 41]
 [64 73]]


## Why Matrix Multiplication Matters in AI

Neural networks represent information using numbers,
vectors, and matrices.

A neural network contains weight matrices.

A simplified view is:

Input
↓
Matrix multiplication with weights
↓
New values
↓
More calculations

Matrix multiplication allows neural networks to
transform numerical representations.

This operation appears throughout neural networks
and Transformer models.

# Day 6 Summary

Today I learned about matrices and their role in AI.

## Key concepts

A matrix is a rectangular arrangement of numbers.

A matrix has rows and columns.

For example:

[
    [1, 2, 3],
    [4, 5, 6]
]

has shape 2 × 3.

## Matrix operations

### Addition

Matrices are added element by element.

Both matrices must have the same shape.

### Subtraction

Matrices are subtracted element by element.

Both matrices must have the same shape.

### Scalar multiplication

A scalar multiplies every element of a matrix.

The shape does not change.

### Matrix multiplication

For:

A = m × n
B = n × p

the multiplication is possible because the inside dimensions match.

The result has shape:

m × p

Matrix multiplication works by taking dot products
between rows of the first matrix and columns of the second matrix.

## NumPy

A * B

means element-wise multiplication.

A @ B

means matrix multiplication.

## Why this matters for AI

Neural networks use vectors and matrices to represent
and transform information.

Matrix multiplication is one of the fundamental operations
used in neural networks and Transformer models.