# Day 7 — Embeddings and Matrix Multiplication

Today we connect embeddings with matrix multiplication.

An embedding is a vector representing a token.

Example:

cat → [0.2, 0.4, 0.6]
dog → [0.1, 0.3, 0.5]
car → [0.7, 0.8, 0.9]

Putting multiple embeddings together creates an embedding matrix.

The matrix has:

rows = tokens
columns = embedding dimensions

## A Sentence as an Embedding Matrix

Suppose:

I → [0.2, 0.1, 0.4]
love → [0.7, 0.3, 0.8]
AI → [0.9, 0.6, 0.2]

The sentence can be represented as:

[
 [0.2, 0.1, 0.4],
 [0.7, 0.3, 0.8],
 [0.9, 0.6, 0.2]
]

This has shape:

3 × 3

3 tokens × 3 embedding dimensions.

In [2]:
import numpy as np

embedding = np.array([
    [0.2, 0.1, 0.4], #I
    [0.7, 0.3, 0.8], #love
    [0.9, 0.6, 0.2]  #AI
])

print("Embeddings: ")
print(embedding)

print("\nShape: ")
print(embedding.shape)


Embeddings: 
[[0.2 0.1 0.4]
 [0.7 0.3 0.8]
 [0.9 0.6 0.2]]

Shape: 
(3, 3)


## Transforming an Embedding

An embedding is an initial numerical representation.

Neural networks transform these representations.

One important operation used for transformation is
matrix multiplication.

Example:

Embedding:

[0.2, 0.1, 0.4]

Weight matrix:

[
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
]

The multiplication is:

(1 × 3) × (3 × 3)

The inside dimensions match, so multiplication is possible.

The result has shape:

1 × 3

For the first output value:

[0.2, 0.1, 0.4] · [1, 4, 7]

= (0.2×1) + (0.1×4) + (0.4×7)

= 3.4

In [3]:
embeddings = np.array([
    [0.2, 0.1, 0.4]
])

weights = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = embeddings @ weights

print("Embedding:")
print(embedding)

print("\nWeights:")
print(weights)

print("\nTransformed embedding:")
print(result)

print("\nResult shape:")
print(result.shape)

Embedding:
[[0.2 0.1 0.4]
 [0.7 0.3 0.8]
 [0.9 0.6 0.2]]

Weights:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transformed embedding:
[[3.4 4.1 4.8]]

Result shape:
(1, 3)


## Understanding Weights

A weight is a number that controls how strongly an input
contributes to an output.

For example:

Input:

[2, 3]

Weights:

[1, 3]

The output is calculated using a dot product:

(2 × 1) + (3 × 3)

= 2 + 9

= 11

Changing the weights changes the output.

Original weights:

[1, 2]

Output:

(2 × 1) + (3 × 2)
= 8

New weights:

[1, 3]

Output:

(2 × 1) + (3 × 3)
= 11

Therefore, weights control how the input is transformed.

In a neural network, these weights are learned during training.

## Bias

A neural network often calculates:

output = input × weights + bias

The input is multiplied by the weights using a dot product.

Example:

Input:

[2, 3]

Weights:

[1, 3]

Bias:

5

Calculation:

(2 × 1) + (3 × 3) + 5

= 2 + 9 + 5

= 16

The bias is an additional value added to the result.

Weights control how strongly inputs contribute to the output.

Bias allows the output to be shifted by an additional amount.

In [5]:
import numpy as np

input_vector = np.array([2,3])
weights = np.array([4,5])
bias = 2

output = np.dot(input_vector, weights) + bias

print("Input:", input_vector)
print("Weights:", weights)
print("Bias:", bias)
print("Output:", output)

Input: [2 3]
Weights: [4 5]
Bias: 2
Output: 25


In [6]:
import numpy as np

input_vector = np.array([2, 3])

weights = np.array([
    [4, 1],
    [5, 2]
])

bias = np.array([2, 1])

output = input_vector @ weights + bias

print("Input:", input_vector)
print("\nWeights:")
print(weights)

print("\nBias:", bias)

print("\nOutput:", output)

Input: [2 3]

Weights:
[[4 1]
 [5 2]]

Bias: [2 1]

Output: [25  9]


In [7]:
import numpy as np

input_vector = np.array([1, 2])

weights = np.array([
    [3, 5],
    [4, 6]
])

bias = np.array([2, 3])

output = input_vector @ weights + bias

print("Input:", input_vector)

print("\nWeights:")
print(weights)

print("\nBias:", bias)

print("\nOutput:", output)

Input: [1 2]

Weights:
[[3 5]
 [4 6]]

Bias: [2 3]

Output: [13 20]
